version: "3.9"

services:
  app:
    container_name: laravel_octane_php
    # image: anterisdev/laravel-swoole:latest
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: php
    volumes:
      - ./src:/var/www/html:delegated
    env_file: .env
    environment:
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
      SWOOLE_WATCH: "yes"
      APP_KEY: "base64:cLrR/eyzu2INrh1r+s9h3uNM4plUmBrYqDyh+D7v6GY="
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - cache
      - db
    ports:
      - 8001:9000

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql

  cache:
    image: redis:alpine
    restart: always

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    ports:
      - "8081:8080"

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=cache
      - REDIS_1_PORT=6379
    depends_on:
      - cache
    ports:
      - "8082:80"

volumes:
  db:
